[package]
name = "imagefork"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["client"]

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
sled = "0.34"
protobuf = "3.2"
quick-protobuf = "0.8.0"
thiserror = "1.0.38"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed = "6.4.2"

[build-dependencies]
protobuf = "3.2"
protobuf-codegen = "3.2"
