[package]
name = "imagefork"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["client"]

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json", "secrets"] }
rocket_db_pools = { version = "0.1.0-rc.2", features = ["sqlx_sqlite"] }
sled = "0.34"
thiserror = "1.0.38"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-embed = "6.4.2"
chrono = { version = "0.4.23", features = ["serde"] }
sqlx = { version = "0.5", features = [
  "macros",
  "runtime-tokio-rustls",
  "sqlite",
  "chrono",
  "migrate",
] }
rocket_oauth2 = { version = "0.5.0-rc.1" }
reqwest = { version = "0.11.14", features = ["tokio-rustls", "json"] }
image = { version = "0.24.5", features = ["libwebp", "rgb"] }
sha2 = "0.10.6"
