[package]
name = "imagefork"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "*", features = ["json", "secrets", "uuid"] }
rocket_prometheus = "*"
rocket_db_pools = { version = "*", features = [
  "diesel_postgres",
  "deadpool_redis",
] }
thiserror = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
rust-embed = "*"
chrono = { version = "*", features = ["serde"] }
reqwest = { version = "*", features = ["tokio-rustls", "json"] }
image = { version = "*", features = ["libwebp", "rgb"] }
sha2 = "*"
rocket_dyn_templates = { version = "*", features = ["handlebars"] }
rand = "*"
base64 = "*"
uuid = { version = "*", features = ["serde"] }
lazy_static = "*"
diesel = { version = "*", features = ["postgres", "chrono"] }
diesel-async = "*"
dotenvy = "*"
rocket_oauth2 = "0.5.0"
