[package]
name = "imagefork"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "*", features = ["with-axum"] }
axum = { version = "*", features = ["tower-log", "macros"] }
axum-prometheus = "*"
base64 = "*"
bb8 = "*"
bb8-redis = "*"
chrono = { version = "*", features = ["serde"] }
diesel = { version = "*", features = ["postgres", "chrono"] }
diesel-async = { version = "*", features = ["postgres", "bb8"] }
figment = { version = "*", features = ["env", "toml"] }
image = { version = "*", features = ["libwebp", "rgb"] }
lazy_static = "*"
mediatype = { version = "*", features = ["serde"] }
metrics = "*"
metrics-exporter-prometheus = "*"
rand = "*"
reqwest = { version = "*", features = ["tokio-rustls", "json"] }
rust-embed = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
sha2 = "*"
thiserror = "*"
tokio = { version = "*", features = ["full"] }
tracing = "*"
tracing-subscriber = { version = "*", features = ["env-filter"] }
uuid = { version = "*", features = ["serde"] }
