apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imagefork-ingress
  labels:
    app: imagefork-core
spec:
  tls:
  - hosts:
    - imagefork.earthmark.dev
    secretName: cloudflare-imagefork.earthmark.dev
  rules:
  - host: imagefork.earthmark.dev
    http:
      paths:
      - path: /redirect
        pathType: Prefix
        backend:
          service:
            name: imagefork-core
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: imagefork-core
  labels:
    app: imagefork-core
spec:
  ports:
    - port: 80
  selector:
    app: imagefork-core
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imagefork-core-config
  labels:
    app: imagefork-core
data:
  ROCKET_PROFILE: production
  ROCKET_PORT: "80"
  ROCKET_ADDRESS: 0.0.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagefork-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagefork-core
  template:
    metadata:
      labels:
        app: imagefork-core
    spec:
      containers:
        - name: imagefork-core
          image: ghcr.io/earthmark/imagefork@sha256:06f71f645a36ee6662e89f6da608ff3d0e086f9e03af0fa4839e24b15367cafa
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          volumeMounts:
          - name: imagefork-core-toml
            mountPath: /usr/local/etc/imagefork/Rocket.toml
            subPath: Rocket.toml
            readOnly: true
          envFrom:
            - configMapRef:
                name: imagefork-core-config
            - secretRef:
                name:  rocket-oauth-github
      volumes:
      - name: imagefork-core-toml
        secret:
          secretName: imagefork-core-toml