apiVersion: v1
kind: Service
metadata:
  name: imagefork-redis
  labels:
    app: imagefork-redis
spec:
  ports:
    - port: 6379
  selector:
    app: imagefork-redis
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imagefork-redis-volume
  labels:
    type: local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/imagefork/redis/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagefork-redis-claim
  labels:
    app: redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment # This should be changed to a stateful set.
metadata:
  name: imagefork-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagefork-redis
  template:
    metadata:
      labels:
        app: imagefork-redis
    spec:
      containers:
        - name: imagefork-redis
          image: redis
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: imagefork-redis-claim