apiVersion: v1
kind: Service
metadata:
  name: imagefork-postgres
  labels:
    app: imagefork-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: imagefork-postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: imagefork-postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: bigolpasswordandstuffyeah # This should be changed to an actual secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: imagefork-postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/imagefork/postgres/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagefork-postgres-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment # This should be changed to a stateful set
metadata:
  name: imagefork-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagefork-postgres
  template:
    metadata:
      labels:
        app: imagefork-postgres
    spec:
      containers:
        - name: imagefork-postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: imagefork-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: imagefork-postgres-claim