[global.authToken]
life_limit = 24
refresh_limit = 3

[global.tokens]
token_keepalive_minutes = 1440 # one day (60 * 24)

[global.oauth.github]
provider = "GitHub"
client_id = "b"
client_secret = "a"
redirect_uri = "http://localhost:8000/auth/github"

[global.databases.imagefork]
url="postgres://postgres:post@localhost/imagefork"

[global.databases.tokens]
url="redis://localhost:6379?ConnectTimeout=5000&IdleTimeOutSecs=180"
